### ISSUE TITLE
[Bug]: No QR Code made

### ISSUE THREAD

**Issue by CascadingSymmetry** [alanhe421/alfred-workflows#428]
### Describe the bug

No QR code appears. I have this error in the debug.

`[4:35:51.441 PM] Logging Started...
[4:35:57.896 PM] QR Reader[Universal Action] Processing complete
[4:35:57.902 PM] QR Reader[Universal Action] Passing output 'https://alfred.app/workflows/alanhe/qr-reader/' to Run Script
[4:35:57.908 PM] STDERR: QR Reader[Run Script] Failed to create file: /Users/kidev/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png
No such file or directory
[4:35:57.909 PM] QR Reader[Run Script] Processing complete
[4:35:57.911 PM] QR Reader[Run Script] Passing output '/Users/me/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png' to Automation Task
[4:35:57.912 PM] ERROR: QR Reader[Automation Task] Task Argument Error: Expecting single or multiple inputs. Warnings: (
    "Passed in file '/Users/me/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png' does not exist, discarding"`

### Workflow Name

QR Reader

### Alfred Version

5.5

### MacOS Version

macOS 14 Sonoma

### Mac Chip

Apple Silicon (like M1, M2)

### MacOS Locale

EN

-----

Workflow Homepage is 👉 [QR Reader](https://github.com/alanhe421/alfred-workflows/tree/master/qr-reader)

**Comment by alanhe421** [comment]
> ### Describe the bug
> No QR code appears. I have this error in the debug.
> 
> `[4:35:51.441 PM] Logging Started... [4:35:57.896 PM] QR Reader[Universal Action] Processing complete [4:35:57.902 PM] QR Reader[Universal Action] Passing output 'https://alfred.app/workflows/alanhe/qr-reader/' to Run Script [4:35:57.908 PM] STDERR: QR Reader[Run Script] Failed to create file: /Users/kidev/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png No such file or directory [4:35:57.909 PM] QR Reader[Run Script] Processing complete [4:35:57.911 PM] QR Reader[Run Script] Passing output '/Users/me/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png' to Automation Task [4:35:57.912 PM] ERROR: QR Reader[Automation Task] Task Argument Error: Expecting single or multiple inputs. Warnings: ( "Passed in file '/Users/me/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cn.alanhe.qr-reader/temp.png' does not exist, discarding"`
> 
> ### Workflow Name
> QR Reader
> 
> ### Alfred Version
> 5.5
> 
> ### MacOS Version
> macOS 14 Sonoma
> 
> ### Mac Chip
> Apple Silicon (like M1, M2)
> 
> ### MacOS Locale
> EN
> 
> Workflow Homepage is 👉 [QR Reader](https://github.com/alanhe421/alfred-workflows/tree/master/qr-reader)


Thank you for your feedback.

Here is a bug, the temporary directory was not initialized automatically when creating qrcode. Here I have submitted a new version.

You can wait for the workflow update to be prompted in the gallery, there will be a delay. Or you can manually download the latest version from this repo and install it to fix it.
