### ISSUE TITLE
[Feat]: Mark "Message" as read

### ISSUE THREAD

**Issue by gungazoo** [alanhe421/alfred-workflows#431]
### Describe the need

Mark the message with the 2FA code as read

### Describe the solution

I'm not sure if it is possible, but if when pulling the 2FA code (which is great by the way) from a message could you also mark _that_ message as read?

Thanks

### Workflow Name

2FA-Read Code

**Comment by alanhe421** [comment]
Yes, this needs to be investigated for feasibility.

**Comment by alanhe421** [comment]
<img width="718" alt="image" src="https://github.com/user-attachments/assets/66835a9a-8caa-4959-9559-4710cf5f9d87">



I have updated the version
1. for unread messages, there will be an icon to distinguish them. 2.
2. when entering to check the captcha, the corresponding message will be marked as read, so it will not be shown as unread when triggered again. However, there is still a problem where the message status does not change in the message app, which I haven't found a solution for yet.
