### ISSUE TITLE
[Bug]: About Mac has a random Automation Task in the canvas

### ISSUE THREAD

**Issue by vitorgalvao** [alanhe421/alfred-workflows#433]
### Describe the bug

In version 1.20, there’s an empty Automation Task object on the canvas which does nothing.

### Workflow Name

About Mac

### Alfred Version

N/A

### MacOS Version

macOS 14 Sonoma

### Mac Chip

Intel

### MacOS Locale

None

-----

Workflow Homepage is 👉 [About Mac](https://github.com/alanhe421/alfred-workflows/tree/master/about-mac)

**Comment by alanhe421** [comment]
thank you @vitorgalvao 

I fixed it.
